name: inside_api
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_wordpress:
    git:
      url: https://github.com/yringler/flutter_wordpress/
      ref: b7827495f4ccf0d5ab555018ae4849c09034989a
  #  path: ../flutter_wordpress
  html: ^0.15.0
  json_annotation: ^4.0.1
  hive: ^2.0.2
  http: ^0.13.1
  http_parser: ^4.0.0
  process_run: ^0.12.1
  path: ^1.8.0
  html_unescape: ^2.0.0
dev_dependencies:
  pedantic: ^1.11.0
  json_serializable: ^4.1.0
  hive_generator: ^1.0.1
  build_runner: ^1.12.2